---
collections:
- name: ansible.netcommon
  version: '=6.1.3'
- name: ansible.posix
  version: '=1.6.1'
- name: ansible.utils
  version: '=4.1.0'
- name: ansible.windows
  version: '=2.4.0'
- name: community.crypto
  version: '=2.26.6'
- name: community.general
  version: '=9.5.13'
- name: community.docker
  version: '=3.13.10'
- name: community.network
  version: '=5.1.0'
- name: community.hashi_vault
  version: '=6.2.1'
- name: community.sops
  version: '=1.9.5'
- name: community.libvirt
  version: '=2.0.0'
- name: community.mysql
  version: '=4.0.1'
- name: community.postgresql
  version: '=4.2.0'
- name: community.mongodb
  version: '=1.7.11'
- name: community.rabbitmq
  version: '=1.6.0'
- name: community.proxysql
  version: '=1.7.0'
- name: community.windows
  version: '=2.2.0'
- name: community.dns
  version: '=3.5.0'
- name: containers.podman
  version: '=1.18.1'
#- name: openstack.cloud
#  version: '<=2.5.0'
#- name: community.kubernetes
#  version: '<=2.0.1'
#- name: community.okd
#  version: '<=5.0.0'
